language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - ree
before_script:
  - 'git clone git://github.com/puppetlabs/puppetlabs-apt.git spec/fixtures/modules/apt'
env:
  - PUPPET_VERSION=2.6.2
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.19
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.14
